version: '3'

networks:
    nginx-php74-mysql8-node:

services:

    # nginx
    nginx-service:
        image: nginx:stable-alpine
        container_name: nginx-container
        ports:
            - "8080:80"
        volumes:
            - ./app:/var/www/project
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php74-service
            - mysql
        networks:
            - nginx-php74-mysql8-node

    # php
    php74-service:
        build:
            context: .
            dockerfile: ./php/Dockerfile
        container_name: php74-container
        ports:
            - "9000:9000"
        volumes:
            - ./app:/var/www/project
        networks:
            - nginx-php74-mysql8-node

    # mysql
    mysql:
        container_name: mysql
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - ./db_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: symfony
            MYSQL_USER: symfony
            MYSQL_PASSWORD: secret
        ports:
            - 3306:3306 
        networks:
            - nginx-php74-mysql8-node

    # node
    node-service:
        image: node:latest
        container_name: node-container
        volumes:
            - ./app:/var/www/project
        working_dir: /var/www/project
        networks:
            - nginx-php74-mysql8-node

    #mailer
    mailer:
        container_name: mailer
        image: mailhog/mailhog
        restart: always
        logging:
            driver: "none"
        ports: 
            - "8025:8025"
            - "1025:1025"
        networks:
            - nginx-php74-mysql8-node